### ISSUE TITLE
Unable to fetch metrics, SSL errors despite setting environment variable to disable it

### ISSUE THREAD

**Issue by Isolyth** [esanchezm/prometheus-qbittorrent-exporter#63] opened 2024-10-10 23:34 UTC
Here is the docker compose file I'm using
```
qbittorrent-exporter:
    image: esanchezm/prometheus-qbittorrent-exporter
    environment:
      - VERIFY_WEBUI_CERTIFICATE=False
      - QBITTORRENT_HOST=192.168.10.3
      - QBITTORRENT_PORT=8088
      - QBITTORRENT_USER=admin
      - QBITTORRENT_PASSWORD=password
    ports:
      - 8000:8000
```
However, when I run my stack, I get endless repeats of 
`{"asctime": "2024-10-10 23:31:52", "levelname": "WARNING", "message": "Retrying (Retry(total=0, connect=1, read=1, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /api/v2/sync/maindata", "taskName": null}`
and 
`{"asctime": "2024-10-10 23:31:38", "levelname": "ERROR", "message": "Couldn't fetch torrents: Failed to connect to qBittorrent. This is likely due to using an untrusted certificate (likely self-signed) for HTTPS qBittorrent WebUI. To suppress this error (and skip certificate verification consequently exposing the HTTPS connection to man-in-the-middle attacks), set VERIFY_WEBUI_CERTIFICATE=False when instantiating Client or set environment variable QBITTORRENTAPI_DO_NOT_VERIFY_WEBUI_CERTIFICATE to a non-null value. SSL Error: SSLError(MaxRetryError(\"HTTPSConnectionPool(host='192.168.10.3', port=8088): Max retries exceeded with url: /api/v2/torrents/info (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))\"))", "taskName": null}`

**Comment by esanchezm** [comment] 2024-10-11 08:19
Hey @990xan ! thanks for the report. That's weird... To confirm the issue is in the exporter code, can you add this to the environment?

```yaml
      - QBITTORRENTAPI_DO_NOT_VERIFY_WEBUI_CERTIFICATE=1
```

Also, if that doesn't work either try removing the `VERIFY_WEBUI_CERTIFICATE=False` too.

**Comment by 990xan** [comment] 2024-10-15 07:33
I've tried it with both and either option, still having the same SSL error... I'll likely be getting a domain soon to setup SSL but it would still be nice to figure out what's going on here

**Comment by esanchezm** [comment] 2024-10-15 12:32
@990xan I ran some local tests I can confirm it works as expected. Are you sure you're using the latest version? The latest version is `1.5.1`

Another thing you can try is increase the verbose level by setting the env variable `EXPORTER_LOG_LEVEL=DEBUG` and then try again.

You can see in the screenshot how it fails with `VERIFY_WEBUI_CERTIFICATE=True` and how it works with `VERIFY_WEBUI_CERTIFICATE=False`

![exporter-ssl](https://github.com/user-attachments/assets/94381355-270c-45f9-9569-66db8a9b43c6)

**Comment by esanchezm** [comment] 2024-10-25 09:09
@Isolyth I'll close this bug for now as I can't reproduce it. Please feel free to reopen it if you can provide more details so I can help you

**Closed by esanchezm** 2024-10-25 09:09 UTC
